import type { AdminDashboardReport } from '../../../services/adminApi'
import type { GateCustomerType, GateSession, GateVehicleType } from '../../../services/staffGateApi'
import { formatSessionSpot } from '../../staff/data/staffGateUtils'
import { AdminStatCard } from '../common/AdminStatCard'
import { AdminStatusBadge } from '../common/AdminStatusBadge'
import { formatAdminCurrency } from '../adminData'
import { formatOperationDateTime, getOperationStaffName, OperationEmpty, OperationField, OperationInfoCell, OperationListShell } from '../operations/AdminOperationPrimitives'
import { Card, CardContent } from '../../ui/card'
import { Input } from '../../ui/input'
import { NativeSelect, NativeSelectOption } from '../../ui/native-select'
export type AdminGateVehicleFilter = 'all' | GateVehicleType
export type AdminGateCustomerFilter = 'all' | GateCustomerType
export function AdminGateLogFilters(p: { query: string; vehicleFilter: AdminGateVehicleFilter; customerFilter: AdminGateCustomerFilter; onQueryChange: (v: string) => void; onVehicleFilterChange: (v: AdminGateVehicleFilter) => void; onCustomerFilterChange: (v: AdminGateCustomerFilter) => void }) { return <Card className="w-full xl:min-w-[46rem]"><CardContent className="grid gap-3 p-4 md:grid-cols-3"><OperationField label="Tìm biển số"><Input value={p.query} onChange={(e) => p.onQueryChange(e.target.value)} placeholder="Ví dụ: 51G-882.14" /></OperationField><OperationField label="Loại xe"><NativeSelect value={p.vehicleFilter} onChange={(e) => p.onVehicleFilterChange(e.target.value as AdminGateVehicleFilter)}><NativeSelectOption value="all">Tất cả</NativeSelectOption><NativeSelectOption value="motorcycle">Xe máy</NativeSelectOption><NativeSelectOption value="car">Ô tô</NativeSelectOption></NativeSelect></OperationField><OperationField label="Loại khách"><NativeSelect value={p.customerFilter} onChange={(e) => p.onCustomerFilterChange(e.target.value as AdminGateCustomerFilter)}><NativeSelectOption value="all">Tất cả</NativeSelectOption><NativeSelectOption value="resident">Cư dân</NativeSelectOption><NativeSelectOption value="walk_in">Khách vãng lai</NativeSelectOption></NativeSelect></OperationField></CardContent></Card> }
export function AdminGateLogStats({ dashboard, isLoading }: { dashboard: AdminDashboardReport | null; isLoading: boolean }) { const a = dashboard?.activity; return <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><AdminStatCard label="Đang trong bãi" value={isLoading ? '-' : a?.activeSessions ?? 0} detail="Phiên đang hoạt động" tone="emerald" /><AdminStatCard label="Xe vào hôm nay" value={isLoading ? '-' : a?.checkinsToday ?? 0} detail="Tổng lượt check-in" tone="sky" /><AdminStatCard label="Xe ra hôm nay" value={isLoading ? '-' : a?.checkoutsToday ?? 0} detail="Tổng lượt check-out" tone="violet" /><AdminStatCard label="Doanh thu hôm nay" value={isLoading ? '-' : formatAdminCurrency(dashboard?.revenueToday.total ?? 0)} detail="Tất cả nguồn thanh toán" tone="amber" /></div> }
export function AdminGateLogList({ sessions, isLoading }: { sessions: GateSession[]; isLoading: boolean }) { if (isLoading) return <OperationEmpty text="Đang tải hoạt động cổng..." />; if (!sessions.length) return <OperationEmpty text="Không có phiên gửi xe phù hợp." />; return <OperationListShell eyebrow="Giám sát trực tiếp" title="Xe đang trong bãi" count={`${sessions.length} xe`} tone="gate">{sessions.map((s) => <Card key={s._id}><CardContent className="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-6 lg:items-center"><div><p className="font-semibold">{s.licensePlate}</p><p className="text-xs text-muted-foreground">{s._id}</p></div><OperationInfoCell label="Phân loại" value={s.vehicleType === 'car' ? 'Ô tô' : 'Xe máy'} detail={s.customerType === 'resident' ? 'Cư dân' : 'Khách vãng lai'} /><OperationInfoCell label="Vị trí" value={formatSessionSpot(s)} /><OperationInfoCell label="Nhân viên" value={getOperationStaffName(s.staffId)} /><OperationInfoCell label="Thời gian vào" value={formatOperationDateTime(s.entryTime)} /><AdminStatusBadge status="active" label="Trong bãi" /></CardContent></Card>)}</OperationListShell> }
