import type { AdminSubscription } from '../../../services/adminApi'
import { isSubscriptionExpiringSoon } from '../../../utils/managerSubscriptionUi'
import { AdminStatCard } from '../common/AdminStatCard'
import { AdminStatusBadge } from '../common/AdminStatusBadge'
import { formatOperationDate, OperationEmpty, OperationInfoCell, OperationListShell } from '../operations/AdminOperationPrimitives'
import { Card, CardContent } from '../../ui/card'
import { Input } from '../../ui/input'
import { NativeSelect, NativeSelectOption } from '../../ui/native-select'
export type AdminSubscriptionStatusFilter = AdminSubscription['status'] | 'all' | 'expiring'
export type AdminSubscriptionVehicleFilter = AdminSubscription['vehicleType'] | 'all'
export function AdminSubscriptionFilters(p: { query: string; status: AdminSubscriptionStatusFilter; vehicleType: AdminSubscriptionVehicleFilter; onQueryChange: (v: string) => void; onStatusChange: (v: AdminSubscriptionStatusFilter) => void; onVehicleTypeChange: (v: AdminSubscriptionVehicleFilter) => void }) { return <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-3"><Input type="search" value={p.query} onChange={(e) => p.onQueryChange(e.target.value)} placeholder="Tên, email, SĐT hoặc biển số" /><NativeSelect value={p.status} onChange={(e) => p.onStatusChange(e.target.value as AdminSubscriptionStatusFilter)}><NativeSelectOption value="all">Tất cả trạng thái</NativeSelectOption><NativeSelectOption value="active">Đang hoạt động</NativeSelectOption><NativeSelectOption value="expiring">Sắp hết hạn</NativeSelectOption><NativeSelectOption value="pending">Chờ thanh toán</NativeSelectOption><NativeSelectOption value="expired">Đã hết hạn</NativeSelectOption><NativeSelectOption value="cancelled">Đã hủy</NativeSelectOption></NativeSelect><NativeSelect value={p.vehicleType} onChange={(e) => p.onVehicleTypeChange(e.target.value as AdminSubscriptionVehicleFilter)}><NativeSelectOption value="all">Tất cả loại xe</NativeSelectOption><NativeSelectOption value="motorcycle">Xe máy</NativeSelectOption><NativeSelectOption value="car">Ô tô</NativeSelectOption></NativeSelect></CardContent></Card> }
export function AdminSubscriptionStats({ subscriptions, activePlates, snapshotTime }: { subscriptions: AdminSubscription[]; activePlates: Set<string>; snapshotTime: number }) { return <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><AdminStatCard label="Tổng đăng ký" value={subscriptions.length} detail={`${subscriptions.filter((x) => x.status === 'pending').length} chờ thanh toán`} tone="violet" /><AdminStatCard label="Gói hoạt động" value={subscriptions.filter((x) => x.status === 'active').length} detail={`${subscriptions.filter((x) => x.status === 'expired').length} đã hết hạn`} tone="emerald" /><AdminStatCard label="Sắp hết hạn" value={subscriptions.filter((x) => isSubscriptionExpiringSoon(x, snapshotTime)).length} detail="Còn tối đa 7 ngày" tone="amber" /><AdminStatCard label="Xe gói trong bãi" value={subscriptions.filter((x) => activePlates.has(x.licensePlate)).length} detail="Có phiên đang hoạt động" tone="sky" /></div> }
export function AdminSubscriptionList({ subscriptions, activePlates, snapshotTime, loading }: { subscriptions: AdminSubscription[]; activePlates: Set<string>; snapshotTime: number; loading: boolean }) { if (loading) return <OperationEmpty text="Đang tải người dùng gói..." />; if (!subscriptions.length) return <OperationEmpty text="Không tìm thấy người dùng gói phù hợp." />; return <OperationListShell eyebrow="Danh sách" title="Người đã đăng ký gói" count={`${subscriptions.length} gói`} tone="gate">{subscriptions.map((x) => { const owner = x.userId && typeof x.userId !== 'string' ? x.userId : null; const plan = x.planId && typeof x.planId !== 'string' ? x.planId : null; const slot = x.slotId && typeof x.slotId !== 'string' ? x.slotId : null; const remaining = x.status === 'active' && x.endDate ? Math.max(0, Math.ceil((new Date(x.endDate).getTime() - snapshotTime) / 86_400_000)) : null; return <Card key={x._id}><CardContent className="grid gap-4 p-4 sm:grid-cols-2 xl:grid-cols-[1.15fr_1fr_1fr_1fr_auto] xl:items-center"><div><p className="font-semibold">{x.licensePlate}</p><p className="text-xs text-muted-foreground">{x.vehicleType === 'car' ? 'Ô tô' : 'Xe máy'}{slot?.slotCode ? ` · ${slot.slotCode}` : ''}</p></div><OperationInfoCell label="Người mua" value={owner?.fullName ?? 'Không xác định'} detail={owner?.email ?? owner?.phone ?? '-'} /><OperationInfoCell label="Gói đăng ký" value={plan?.name ?? plan?.code ?? 'Không xác định'} detail={`${plan?.durationDays ?? 0} ngày sử dụng`} /><OperationInfoCell label="Thời hạn" value={`${formatOperationDate(x.startDate)} - ${formatOperationDate(x.endDate)}`} detail={remaining === null ? 'Chưa bắt đầu' : `Còn ${remaining} ngày`} /><div className="flex flex-wrap gap-2"><AdminStatusBadge status={x.status} />{activePlates.has(x.licensePlate) && <AdminStatusBadge status="active" label="Trong bãi" />}</div></CardContent></Card> })}</OperationListShell> }

