import { useEffect, useState, type FormEvent } from 'react'
import type { ManagerPlan, ManagerPlanUpdatePayload } from '../../../services/managerPlansApi'
import { AdminStatCard } from '../common/AdminStatCard'
import { AdminStatusBadge } from '../common/AdminStatusBadge'
import { formatAdminCurrency } from '../adminData'
import { OperationEmpty, OperationField, operationInputClass } from '../operations/AdminOperationPrimitives'

export type AdminPlanVehicleFilter = 'all' | ManagerPlan['vehicleType']
export type AdminPlanStatusFilter = 'all' | 'active' | 'inactive'

export function AdminPlanFilters({ vehicleFilter, statusFilter, onVehicleFilterChange, onStatusFilterChange }: { vehicleFilter: AdminPlanVehicleFilter; statusFilter: AdminPlanStatusFilter; onVehicleFilterChange: (value: AdminPlanVehicleFilter) => void; onStatusFilterChange: (value: AdminPlanStatusFilter) => void }) {
  return <div className="grid w-full gap-3 rounded-2xl border border-theme bg-page/55 p-3 shadow-sm backdrop-blur-sm sm:grid-cols-2 xl:min-w-[30rem]"><OperationField label="Loại xe"><select className="h-11 rounded-xl border border-theme bg-page px-3 text-sm text-fg" value={vehicleFilter} onChange={(event) => onVehicleFilterChange(event.target.value as AdminPlanVehicleFilter)}><option value="all">Tất cả</option><option value="motorcycle">Xe máy</option><option value="car">Ô tô</option></select></OperationField><OperationField label="Trạng thái"><select className="h-11 rounded-xl border border-theme bg-page px-3 text-sm text-fg" value={statusFilter} onChange={(event) => onStatusFilterChange(event.target.value as AdminPlanStatusFilter)}><option value="all">Tất cả</option><option value="active">Đang hoạt động</option><option value="inactive">Đã tắt</option></select></OperationField></div>
}

export function AdminPlanStats({ plans, isLoading }: { plans: ManagerPlan[]; isLoading: boolean }) {
  return <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><AdminStatCard label="Tổng gói" value={isLoading ? '-' : plans.length} detail="Tất cả loại xe" tone="violet" /><AdminStatCard label="Đang hoạt động" value={isLoading ? '-' : plans.filter((item) => item.isActive).length} detail="Có thể đăng ký" tone="emerald" /><AdminStatCard label="Gói xe máy" value={isLoading ? '-' : plans.filter((item) => item.vehicleType === 'motorcycle').length} detail="Dùng sức chứa chung" tone="sky" /><AdminStatCard label="Gói ô tô" value={isLoading ? '-' : plans.filter((item) => item.vehicleType === 'car').length} detail="Chọn ô cố định" tone="amber" /></div>
}

export function AdminPlanList({ plans, isLoading, updatingId, onEdit, onToggle }: { plans: ManagerPlan[]; isLoading: boolean; updatingId: string | null; onEdit: (plan: ManagerPlan) => void; onToggle: (plan: ManagerPlan) => void }) {
  if (isLoading) return <OperationEmpty text="Đang tải danh sách gói..." />
  if (!plans.length) return <OperationEmpty text="Không có gói phù hợp." />
  return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{plans.map((plan) => <article key={plan._id} className="liquid-glass-card group rounded-2xl border border-violet-500/10 p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:border-violet-500/25 hover:shadow-xl"><span className={`absolute inset-x-0 top-0 h-1 ${plan.vehicleType === 'car' ? 'bg-gradient-to-r from-violet-500 to-fuchsia-500' : 'bg-gradient-to-r from-sky-500 to-emerald-500'}`} /><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-violet-600 dark:text-violet-300">{plan.code}</p><h2 className="mt-2 text-xl font-black text-fg">{plan.name}</h2></div><AdminStatusBadge status={plan.isActive ? 'active' : 'inactive'} /></div><p className="mt-5 text-3xl font-black tracking-tight text-fg">{formatAdminCurrency(plan.price)}</p><p className="mt-1 text-xs font-medium text-muted">{plan.durationDays} ngày · {plan.vehicleType === 'car' ? 'Ô tô' : 'Xe máy'}</p><p className="mt-4 min-h-12 text-sm leading-6 text-muted">{plan.description || 'Không có mô tả.'}</p><div className="mt-5 flex gap-2 border-t border-theme pt-4"><button className="h-11 flex-1 rounded-xl border border-violet-500/25 bg-violet-500/10 text-sm font-bold text-violet-700" onClick={() => onEdit(plan)}>Chỉnh sửa</button><button className={`h-11 flex-1 rounded-xl text-sm font-bold text-white disabled:opacity-50 ${plan.isActive ? 'bg-amber-500' : 'bg-emerald-500'}`} disabled={updatingId === plan._id} onClick={() => onToggle(plan)}>{updatingId === plan._id ? 'Đang lưu...' : plan.isActive ? 'Tạm dừng' : 'Kích hoạt'}</button></div></article>)}</section>
}

export function AdminPlanFormModal({ plan, isSubmitting, error, onClose, onSubmit }: { plan: ManagerPlan | null; isSubmitting: boolean; error: string | null; onClose: () => void; onSubmit: (payload: ManagerPlanUpdatePayload) => void }) {
  const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [durationDays, setDurationDays] = useState(''); const [description, setDescription] = useState('')
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (plan) { setName(plan.name); setPrice(String(plan.price)); setDurationDays(String(plan.durationDays)); setDescription(plan.description ?? '') } }, [plan])
  if (!plan) return null
  function submit(event: FormEvent) { event.preventDefault(); onSubmit({ name: name.trim(), price: Number(price), durationDays: Number(durationDays), description: description.trim() }) }
  return <div className="fixed inset-0 z-[80] grid place-items-center bg-overlay p-4" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="liquid-glass-card w-full max-w-lg rounded-2xl p-5" onSubmit={submit}><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[0.18em] text-subtle">Admin // Gói gửi xe</p><h2 className="mt-2 text-xl font-semibold text-fg">Chỉnh sửa gói</h2></div><button type="button" className="text-muted" onClick={onClose}>✕</button></div><div className="mt-5 grid gap-4"><OperationField label="Tên gói"><input className={operationInputClass} value={name} onChange={(event) => setName(event.target.value)} required /></OperationField><div className="grid gap-4 sm:grid-cols-2"><OperationField label="Giá"><input className={operationInputClass} type="number" min="0" value={price} onChange={(event) => setPrice(event.target.value)} required /></OperationField><OperationField label="Thời hạn (ngày)"><input className={operationInputClass} type="number" min="1" value={durationDays} onChange={(event) => setDurationDays(event.target.value)} required /></OperationField></div><OperationField label="Mô tả"><textarea className="min-h-24 rounded-lg border border-theme bg-page p-3 text-sm text-fg" value={description} onChange={(event) => setDescription(event.target.value)} /></OperationField>{error && <p className="text-sm text-rose-300">{error}</p>}</div><div className="mt-5 flex justify-end gap-2"><button type="button" className="h-10 rounded-lg border border-theme px-4 text-sm text-fg" onClick={onClose}>Hủy</button><button className="h-10 rounded-lg bg-btn-primary px-4 text-sm font-semibold text-btn-primary-fg disabled:opacity-50" disabled={isSubmitting}>{isSubmitting ? 'Đang lưu...' : 'Lưu thay đổi'}</button></div></form></div>
}
