import { useState } from 'react'
import { AdminParkingSpaceHeader, AdminParkingSpaceList, AdminRowFormModal, AdminSlotFormModal, AdminStatCard } from '../../components/admin'
import { useManagerParkingSpaces } from '../../hooks/useManagerParkingSpaces'
import { useParkingSpaceFilters } from '../../hooks/useParkingSpaceFilters'
import { parkingRowApi, type ParkingRow, type RowCreatePayload, type RowUpdatePayload } from '../../services/managerParkingRowApi'
import { parkingSlotApi, type ParkingSlot, type SlotBulkCreatePayload, type SlotUpdatePayload } from '../../services/managerParkingSlotApi'
import { Alert, AlertDescription } from '../../components/ui/alert'
export function AdminSlotsPage() {
  const data = useManagerParkingSpaces(); const { slots, rows, floors, buildings, isLoading, error, setError, reloadSlots, reloadRows } = data; const f = useParkingSpaceFilters({ slots, rows, floors, buildings })
  const [slotOpen, setSlotOpen] = useState(false); const [slotMode, setSlotMode] = useState<'create' | 'edit'>('create'); const [activeSlot, setActiveSlot] = useState<ParkingSlot | null>(null); const [rowOpen, setRowOpen] = useState(false); const [rowMode, setRowMode] = useState<'create' | 'edit'>('create'); const [activeRow, setActiveRow] = useState<ParkingRow | null>(null); const [submitting, setSubmitting] = useState(false); const [submitError, setSubmitError] = useState<string | null>(null)
  async function saveSlot(payload: SlotUpdatePayload | SlotBulkCreatePayload | { floorId: string; slotCode: string; vehicleType: 'car'; note?: string }) { setSubmitting(true); setSubmitError(null); try { if (slotMode === 'create') { if ('quantity' in payload) await parkingSlotApi.bulkCreateSlots(payload); else if ('floorId' in payload) await parkingSlotApi.createSlot(payload) } else if (activeSlot) await parkingSlotApi.updateSlot(activeSlot._id, payload as SlotUpdatePayload); await reloadSlots(); setSlotOpen(false) } catch (e) { setSubmitError(e instanceof Error ? e.message : 'Không thể lưu ô đỗ.') } finally { setSubmitting(false) } }
  async function saveRow(payload: RowCreatePayload | RowUpdatePayload) { setSubmitting(true); setSubmitError(null); try { if (rowMode === 'create') await parkingRowApi.createRow(payload as RowCreatePayload); else if (activeRow) await parkingRowApi.updateRow(activeRow._id, payload as RowUpdatePayload); await reloadRows(); setRowOpen(false) } catch (e) { setSubmitError(e instanceof Error ? e.message : 'Không thể lưu hàng xe máy.') } finally { setSubmitting(false) } }
  async function deleteSlot(slot: ParkingSlot) { try { await parkingSlotApi.deleteSlot(slot._id); await reloadSlots() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể xóa ô đỗ.') } }
  return <div className="pb-10"><AdminParkingSpaceHeader buildings={buildings} floors={f.filteredFloorOptions} buildingFilter={f.buildingFilter} floorFilter={f.floorFilter} onBuildingFilterChange={f.setBuildingFilter} onFloorFilterChange={f.setFloorFilter} onCreateSlot={() => { setSlotMode('create'); setActiveSlot(null); setSubmitError(null); setSlotOpen(true) }} onCreateRow={() => { setRowMode('create'); setActiveRow(null); setSubmitError(null); setRowOpen(true) }} /><div className="mx-auto max-w-[118rem] px-4 md:px-8 lg:px-10"><div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><AdminStatCard label="Ô đỗ ô tô" value={f.stats.totalSlots} detail={`${f.stats.occupiedSlots} đang dùng`} tone="violet" /><AdminStatCard label="Hàng xe máy" value={f.stats.totalRows} detail="Tổng số hàng" tone="sky" /><AdminStatCard label="Sức chứa xe máy" value={f.stats.rowCapacity} detail={`${f.stats.rowOccupied} đang dùng`} tone="emerald" /><AdminStatCard label="Bảo trì" value={f.stats.maintenanceSlots} detail="Ô đỗ ô tô" tone="amber" /></div>{error && <Alert variant="destructive" className="mb-4"><AlertDescription>{error}</AlertDescription></Alert>}<AdminParkingSpaceList isLoading={isLoading} hasError={Boolean(error)} filteredSlots={f.filteredSlots} filteredRows={f.filteredRows} visibleSlotFloors={f.visibleSlotFloors} visibleRowFloors={f.visibleRowFloors} slotsByFloor={f.slotsByFloor} rowsByFloor={f.rowsByFloor} buildingMap={f.buildingMap} onEditSlot={(slot) => { setSlotMode('edit'); setActiveSlot(slot); setSubmitError(null); setSlotOpen(true) }} onDeleteSlot={(slot) => void deleteSlot(slot)} onEditRow={(row) => { setRowMode('edit'); setActiveRow(row); setSubmitError(null); setRowOpen(true) }} /></div><AdminSlotFormModal open={slotOpen} mode={slotMode} floors={floors.filter((x) => x.vehicleType === 'car')} initialValues={activeSlot ? { floorId: typeof activeSlot.floorId === 'string' ? activeSlot.floorId : activeSlot.floorId?._id, slotCode: activeSlot.slotCode, vehicleType: activeSlot.vehicleType, status: activeSlot.status, note: activeSlot.note } : undefined} isSubmitting={submitting} error={submitError} onClose={() => setSlotOpen(false)} onSubmit={saveSlot} /><AdminRowFormModal open={rowOpen} mode={rowMode} floors={floors.filter((x) => x.vehicleType === 'motorcycle')} initialValues={activeRow ? { floorId: typeof activeRow.floorId === 'string' ? activeRow.floorId : activeRow.floorId?._id, rowCode: activeRow.rowCode, capacity: activeRow.capacity, note: activeRow.note } : undefined} isSubmitting={submitting} error={submitError} onClose={() => setRowOpen(false)} onSubmit={saveRow} /></div>
}

