import { useEffect, useMemo, useState } from 'react'
import { Search } from 'lucide-react'
import { AdminPageShell, AdminStatCard, AdminStatusBadge } from '../../components/admin'
import { adminApi, type AdminUser } from '../../services/adminApi'
import { Badge } from '../../components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card'
import { Input } from '../../components/ui/input'
import { Label } from '../../components/ui/label'
import { NativeSelect, NativeSelectOption } from '../../components/ui/native-select'
import { Skeleton } from '../../components/ui/skeleton'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/table'

const roleLabels: Record<AdminUser['role'], string> = { admin: 'Admin', manager: 'Manager', staff: 'Nhân viên', user: 'Người dùng' }
const roleDetails: Record<AdminUser['role'], string> = { admin: 'Toàn quyền quản trị và cấu hình hệ thống', manager: 'Quản lý bãi xe, nhân viên và báo cáo', staff: 'Vận hành cổng và xử lý xe vào, ra', user: 'Đặt chỗ và sử dụng gói gửi xe' }

export function UserManagementPage() {
  const [users, setUsers] = useState<AdminUser[]>([]); const [total, setTotal] = useState(0); const [query, setQuery] = useState(''); const [roleFilter, setRoleFilter] = useState<'all' | AdminUser['role']>('all'); const [statusFilter, setStatusFilter] = useState<'all' | 'active' | 'inactive'>('all'); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { let ignore = false; async function load() { try { setIsLoading(true); setError(''); const response = await adminApi.getUsers({ limit: 100, sort: 'createdAt', order: 'desc' }); if (!ignore) { setUsers(response.users ?? []); setTotal(response.total ?? 0) } } catch (err) { if (!ignore) setError(err instanceof Error ? err.message : 'Không thể tải người dùng') } finally { if (!ignore) setIsLoading(false) } } void load(); return () => { ignore = true } }, [])
  const roles = useMemo(() => (['admin', 'manager', 'staff', 'user'] as const).map((role) => ({ role, users: users.filter((u) => u.role === role).length })), [users])
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return users.filter((u) => (!q || u.fullName.toLowerCase().includes(q) || u.email.toLowerCase().includes(q) || u.phone?.toLowerCase().includes(q)) && (roleFilter === 'all' || u.role === roleFilter) && (statusFilter === 'all' || u.isActive === (statusFilter === 'active'))) }, [query, roleFilter, statusFilter, users])
  const active = users.filter((u) => u.isActive).length; const operations = users.filter((u) => u.role === 'manager' || u.role === 'staff').length
  return <AdminPageShell eyebrow="Admin // Người dùng" title="Quản lý người dùng" description="Quản lý tài khoản người dùng, nhân viên, quản lý và admin; kiểm soát vai trò trước khi cho phép truy cập hệ thống." actions={<Card className="w-full xl:min-w-[44rem]"><CardContent className="grid gap-3 p-4 sm:grid-cols-3"><Label className="grid gap-2"><span>Tìm kiếm</span><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tên, email hoặc số điện thoại" /></div></Label><Label className="grid gap-2"><span>Vai trò</span><NativeSelect value={roleFilter} onChange={(e) => setRoleFilter(e.target.value as typeof roleFilter)}><NativeSelectOption value="all">Tất cả vai trò</NativeSelectOption>{roles.map(({ role }) => <NativeSelectOption key={role} value={role}>{roleLabels[role]}</NativeSelectOption>)}</NativeSelect></Label><Label className="grid gap-2"><span>Trạng thái</span><NativeSelect value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as typeof statusFilter)}><NativeSelectOption value="all">Tất cả</NativeSelectOption><NativeSelectOption value="active">Đang hoạt động</NativeSelectOption><NativeSelectOption value="inactive">Đã khóa</NativeSelectOption></NativeSelect></Label></CardContent></Card>}>
    {error && <Card className="mb-5 border-destructive/40"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
    <div className="grid gap-3 md:grid-cols-3"><AdminStatCard label="Tất cả tài khoản" value={isLoading ? '-' : total} detail="Người dùng, nhân viên, quản lý và admin" tone="violet" /><AdminStatCard label="Đội vận hành" value={isLoading ? '-' : operations} detail="Tài khoản quản lý và nhân viên" tone="sky" /><AdminStatCard label="Đang hoạt động" value={isLoading ? '-' : active} detail="Có thể truy cập hệ thống" tone="emerald" /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_23rem]">
      <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Danh sách người dùng</CardTitle><Badge variant="secondary">{filtered.length} tài khoản</Badge></CardHeader><CardContent>{isLoading ? <div className="space-y-3">{Array.from({ length: 6 }, (_, i) => <Skeleton key={i} className="h-14 w-full" />)}</div> : <Table><TableHeader><TableRow><TableHead>Người dùng</TableHead><TableHead>Vai trò</TableHead><TableHead>Điện thoại</TableHead><TableHead>Ngày tạo</TableHead><TableHead>Trạng thái</TableHead></TableRow></TableHeader><TableBody>{!filtered.length ? <TableRow><TableCell colSpan={5} className="h-24 text-center text-muted-foreground">Không tìm thấy người dùng.</TableCell></TableRow> : filtered.map((user) => <TableRow key={user._id}><TableCell><div className="font-medium">{user.fullName}</div><div className="text-xs text-muted-foreground">{user.email}</div></TableCell><TableCell><Badge variant="outline">{roleLabels[user.role]}</Badge></TableCell><TableCell>{user.phone ?? '-'}</TableCell><TableCell>{user.createdAt ? new Date(user.createdAt).toLocaleString('vi-VN') : '-'}</TableCell><TableCell><AdminStatusBadge status={user.isActive ? 'active' : 'inactive'} /></TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Ma trận vai trò</CardTitle></CardHeader><CardContent className="grid gap-3">{roles.map(({ role, users: count }) => <Card key={role} className="shadow-none"><CardContent className="flex items-start justify-between gap-3 p-4"><div><p className="font-medium">{roleLabels[role]}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{roleDetails[role]}</p></div><Badge>{count}</Badge></CardContent></Card>)}</CardContent></Card>
    </div>
  </AdminPageShell>
}

